<?xml version='1.0'?>

<robot name="moving_obs" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="DEG_TO_RAD" value="${PI/180.0}" />

  <xacro:property name="chassisHeight" value="0.5"/>
  <xacro:property name="chassisLength" value="1"/>
  <xacro:property name="chassisWidth" value="1"/>
  <xacro:property name="chassisMass" value="50"/>

  <xacro:property name="wheelWidth" value=".2"/>
  <xacro:property name="wheelRadius" value="0.2"/>
  <xacro:property name="wheelPos" value="0.2"/>
  <xacro:property name="wheelMass" value="5"/>

  <xacro:include filename="$(find project)include/urdf/project.gazebo" />
  <xacro:include filename="$(find project)include/urdf/materials.xacro" />
  <xacro:include filename="$(find project)include/urdf/macros.xacro" />

<link name="base" />
  <joint name="base_joint" type="fixed">
    <parent link="base"/>
    <child link="chassis"/>
    <origin rpy="0 0 0" xyz="0 0 ${2*wheelRadius+chassisHeight/2}"/>
  </joint>

  <link name="chassis">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
  <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
  <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${chassisMass}"/>
      <box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>
</link>
<wheel lr="1" tY="1"/>
<wheel lr="1" tY="-1"/>
<wheel lr="-1" tY="-1"/>
<wheel lr="-1" tY="1"/>
  

</robot>

